apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "codeready-workspaces"
  namespace: "codeready" 
spec:
  channel: "latest" 
  installPlanApproval: "Automatic"
  source: "redhat-operators" 
  sourceNamespace: "openshift-marketplace"
  name: "codeready-workspaces"
  startingCSV: crwoperator.v2.1.1
