apiVersion: v1
kind: Project
metadata:
  name: knative-serving
  labels:
    kiali.io/member-of: istio-system
    maistra.io/member-of: istio-system
spec:
  finalizers:
    - kubernetes
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  labels: {}
  namespace: knative-serving
spec: {}
